"""
Ultra96 FPGA inference for Wine MLP (int4, ap_fixed<12,4>).
Requires test_data.json generated by generate_test_data.py on the host.
"""
import mmap
import struct
import time
import json

UIO_DEV  = "/dev/uio4"
MAP_SIZE = 0x10000
REG_OUT  = 0x10   # layer6_out base offset
REG_IN   = 0x20   # x base offset

# ap_fixed<12,4>: 4 integer bits, 8 fractional bits
FRAC = 8

def to_fixed(val):
    raw = int(round(val * (1 << FRAC)))
    raw = max(-2048, min(2047, raw))
    return raw & 0xFFF

def from_fixed(raw):
    raw &= 0xFFF
    if raw >= 2048:
        raw -= 4096
    return raw / (1 << FRAC)

def read32(mm, off):
    mm.seek(off)
    return struct.unpack('<I', mm.read(4))[0]

def write32(mm, off, val):
    mm.seek(off)
    mm.write(struct.pack('<I', val))

def write_inputs(mm, x):
    fixed = [to_fixed(v) for v in x]
    for n in range(7):  # ceil(13/2) = 7 words
        even = fixed[2*n]   if 2*n   < 13 else 0
        odd  = fixed[2*n+1] if 2*n+1 < 13 else 0
        write32(mm, REG_IN + n*4, (odd << 16) | even)

def read_outputs(mm):
    out = []
    for n in range(2):  # ceil(3/2) = 2 words
        word = read32(mm, REG_OUT + n*4)
        out.append(from_fixed(word & 0xFFF))
        if 2*n+1 < 3:
            out.append(from_fixed((word >> 16) & 0xFFF))
    return out[:3]

def predict(mm, x_scaled):
    write_inputs(mm, x_scaled)
    time.sleep(0.001)
    scores = read_outputs(mm)
    return scores, scores.index(max(scores))


with open("/home/root/fpga/test_scripts/wine/wine_test_data.json") as f:
    data = json.load(f)

X, y, names = data["X"], data["y"], data["names"]

with open(UIO_DEV, 'r+b', buffering=0) as f:
    mm = mmap.mmap(f.fileno(), MAP_SIZE)

    correct = 0
    for i in range(len(X)):
        scores, pred = predict(mm, X[i])
        if pred == y[i]:
            correct += 1

    print(f"Accuracy FPGA: {correct}/{len(y)} = {correct/len(y)*100:.1f}%")

    print("\n--- Primeras 5 muestras ---")
    for i in range(5):
        scores, pred = predict(mm, X[i])
        status = "OK" if pred == y[i] else "FAIL"
        print(f"[{i}] real={names[y[i]]:<20} pred={names[pred]:<20} "
              f"scores={[round(s,2) for s in scores]} {status}")

    scores, pred = predict(mm, [7.4, 0.70, 0.00, 1.9, 0.076, 11.0, 34.0, 0.9978, 3.51, 0.56, 9.4, 5.0, 0.0])
    print(f"AXI-Lite scores: {scores}, pred={pred}")

    mm.close()
