#!/usr/bin/env python3
"""Generate wine_test_data.h from wine_test_data.json.

The C test harness has no JSON parser, so the wine test set (178 samples,
13 standardized features, 3 classes) is embedded as static arrays at
compile time. Re-run this script if wine_test_data.json changes.

Usage: python3 gen_wine_test_data.py
"""
import json
import os

SRC = os.path.join(os.path.dirname(__file__),
                    "..", "..", "FPGA-files", "test_scripts", "wine", "wine_test_data.json")
DST = os.path.join(os.path.dirname(__file__), "wine_test_data.h")


def main():
    with open(SRC) as f:
        data = json.load(f)
    X, y = data["X"], data["y"]
    n, n_in = len(X), len(X[0])

    with open(DST, "w") as f:
        f.write("/* Auto-generated by gen_wine_test_data.py from wine_test_data.json. Do not edit by hand. */\n")
        f.write("#ifndef WINE_TEST_DATA_H\n#define WINE_TEST_DATA_H\n\n")
        f.write(f"#define WINE_N_SAMPLES {n}\n")
        f.write(f"#define WINE_N_FEATURES {n_in}\n\n")
        f.write(f"static const float WINE_X[WINE_N_SAMPLES][WINE_N_FEATURES] = {{\n")
        for row in X:
            f.write("    {" + ", ".join(f"{v:.8g}f" for v in row) + "},\n")
        f.write("};\n\n")
        f.write(f"static const int WINE_Y[WINE_N_SAMPLES] = {{\n    ")
        f.write(", ".join(str(v) for v in y))
        f.write("\n};\n\n")
        f.write("#endif /* WINE_TEST_DATA_H */\n")

    print(f"Wrote {DST}: {n} samples x {n_in} features")


if __name__ == "__main__":
    main()
