"""
GTSRB FPGA inference via AXI-DMA + UIO.

STATUS: TEMPLATE — requires a synthesized bitstream.
        Fill in the constants in the CONFIG section before use.

Difference from wine_infer.py (AXI-Lite):
  The GTSRB model uses hls4ml io_stream, which exposes AXI-Stream ports.
  The DMA block bridges Linux and the accelerator:
    PS (mmap DMA buffer) → AXI-Stream → HLS4ML CNN → AXI-Stream → PS

Requirements on the Ultra96:
  1. Bitstream generated by the hls4ml VivadoAccelerator backend:
       python dev/hls4ml/convert_model.py --model gtsrb_gap --mode int8 \
              --backend VivadoAccelerator --build --synth
  2. Device Tree Overlay with:
       - xlnx,axi-dma-1.00.a compatible under /amba
       - hls4ml accelerator under /amba
  3. UIO modules loaded (same as wine_infer.py):
       modprobe uio && modprobe uio_pdrv_genirq of_id=generic-uio

Data flow:
  1. Write the normalized image (3×64×64 = 12288 float32) to the TX DMA buffer
  2. Start the S2MM transfer (MM2S → accelerator → S2MM)
  3. Read 43 int32 logits from the RX DMA buffer
  4. Argmax → predicted class

References:
  - AXI DMA PG021 (Xilinx)
  - hls4ml VivadoAccelerator docs: https://fastmachinelearning.org/hls4ml/
"""

import json
import mmap
import os
import struct
import sys
import time

import numpy as np

# ---------------------------------------------------------------------------
# CONFIG — fill in after generating the bitstream
# ---------------------------------------------------------------------------

# AXI DMA base address (see /proc/device-tree or read the .xsa)
DMA_BASE   = 0x80000000   # placeholder
DMA_SIZE   = 0x10000

# HLS4ML accelerator base address (ap_ctrl register)
HLS_BASE   = 0xA0010000   # placeholder
HLS_SIZE   = 0x10000

# Contiguous DMA buffers (reserve with /dev/mem or the dma-proxy module)
TX_BUF_PHYS = 0x1E000000  # placeholder — adjust based on available CMA
RX_BUF_PHYS = 0x1E200000  # placeholder

# Number of input and output values
N_IN   = 3 * 64 * 64   # 12288 float32
N_OUT  = 43            # int32 logits (or ap_fixed depending on hls4ml config)

UIO_DMA = "/dev/uio0"   # may vary — check with ls /sys/class/uio/uio*/name

# ---------------------------------------------------------------------------
# GTSRB normalization (same values as used in training)
# ---------------------------------------------------------------------------

MEAN = np.array([0.3337, 0.3064, 0.3171], dtype=np.float32)
STD  = np.array([0.2672, 0.2564, 0.2629], dtype=np.float32)

CLASS_NAMES_PATH = "/home/root/gtsrb_class_names.json"


def preprocess(bgr_crop):
    """BGR crop (any size) → normalized float32 array (3072,)."""
    import cv2
    rgb  = cv2.cvtColor(bgr_crop, cv2.COLOR_BGR2RGB)
    rgb  = cv2.resize(rgb, (64, 64))
    arr  = rgb.astype(np.float32) / 255.0
    arr  = (arr - MEAN) / STD          # (64, 64, 3)
    arr  = arr.transpose(2, 0, 1)      # (3, 64, 64) — channel-first
    return arr.flatten()               # (12288,)


# ---------------------------------------------------------------------------
# AXI DMA helpers (register offsets per PG021)
# ---------------------------------------------------------------------------

MM2S_DMACR   = 0x00
MM2S_DMASR   = 0x04
MM2S_SA      = 0x18   # source address (32-bit physical)
MM2S_LENGTH  = 0x28

S2MM_DMACR   = 0x30
S2MM_DMASR   = 0x34
S2MM_DA      = 0x48   # destination address
S2MM_LENGTH  = 0x58


def dma_write32(mm, off, val):
    mm.seek(off)
    mm.write(struct.pack('<I', val & 0xFFFFFFFF))


def dma_read32(mm, off):
    mm.seek(off)
    return struct.unpack('<I', mm.read(4))[0]


def dma_wait_idle(mm, status_reg, timeout=2.0):
    """Waits until the Idle bit (bit 1) is set to 1."""
    t0 = time.time()
    while True:
        sr = dma_read32(mm, status_reg)
        if sr & 0x2:    # Idle bit
            return True
        if time.time() - t0 > timeout:
            raise TimeoutError(f"DMA timeout  SR=0x{sr:08x}")
        time.sleep(0.0001)


def run_dma_transfer(dma_mm, tx_phys, rx_phys, tx_bytes, rx_bytes):
    """Launches an MM2S+S2MM transfer and waits for both to finish."""
    # Start S2MM first so it's ready when the data arrives
    dma_write32(dma_mm, S2MM_DMACR,  0x1)          # run
    dma_write32(dma_mm, S2MM_DA,     rx_phys)
    dma_write32(dma_mm, S2MM_LENGTH, rx_bytes)

    # Start MM2S
    dma_write32(dma_mm, MM2S_DMACR,  0x1)
    dma_write32(dma_mm, MM2S_SA,     tx_phys)
    dma_write32(dma_mm, MM2S_LENGTH, tx_bytes)

    # Wait for both
    dma_wait_idle(dma_mm, MM2S_DMASR)
    dma_wait_idle(dma_mm, S2MM_DMASR)


# ---------------------------------------------------------------------------
# Inference
# ---------------------------------------------------------------------------

def predict(dma_mm, tx_mem, rx_mem, input_flat):
    """
    input_flat: numpy float32 array (3072,)
    Returns (class_id, logits_array)
    """
    # Write input to the TX buffer (as bytes)
    tx_mem.seek(0)
    tx_mem.write(input_flat.tobytes())

    tx_bytes = N_IN  * 4
    rx_bytes = N_OUT * 4

    run_dma_transfer(dma_mm, TX_BUF_PHYS, RX_BUF_PHYS, tx_bytes, rx_bytes)

    # Read logits from the RX buffer
    rx_mem.seek(0)
    raw = rx_mem.read(rx_bytes)
    logits = np.frombuffer(raw, dtype=np.float32)   # adjust dtype if hls4ml uses int

    cls = int(np.argmax(logits))
    return cls, logits


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if not os.path.exists(UIO_DMA):
        print(f"ERROR: {UIO_DMA} not found.")
        print("Load the overlay and the UIO modules first.")
        sys.exit(1)

    with open(CLASS_NAMES_PATH) as f:
        raw = json.load(f)
    names = [raw[str(i)] for i in range(43)]

    # Map DMA registers
    with open(UIO_DMA, 'r+b', buffering=0) as f:
        dma_mm = mmap.mmap(f.fileno(), DMA_SIZE)

    # Map DMA buffers (needs /dev/mem or the dma-proxy module)
    # If using /dev/mem, adjust the offsets according to your bitstream's memory map
    mem_fd = os.open("/dev/mem", os.O_RDWR | os.O_SYNC)
    tx_mem = mmap.mmap(mem_fd, N_IN  * 4, offset=TX_BUF_PHYS)
    rx_mem = mmap.mmap(mem_fd, N_OUT * 4, offset=RX_BUF_PHYS)

    # --- Demo: use a test image from a file ---
    import cv2
    test_image = sys.argv[1] if len(sys.argv) > 1 else None
    if test_image is None:
        print("Usage: python gtsrb_infer.py sign_image.jpg")
        sys.exit(0)

    bgr = cv2.imread(test_image)
    if bgr is None:
        print(f"Could not open: {test_image}")
        sys.exit(1)

    x = preprocess(bgr)
    t0 = time.time()
    cls, logits = predict(dma_mm, tx_mem, rx_mem, x)
    dt = (time.time() - t0) * 1000

    softmax_probs = np.exp(logits - logits.max())
    softmax_probs /= softmax_probs.sum()

    print(f"Image  : {test_image}")
    print(f"Class  : [{cls:2d}] {names[cls]}")
    print(f"Conf   : {softmax_probs[cls]*100:.1f}%")
    print(f"Time   : {dt:.2f} ms")

    dma_mm.close()
    tx_mem.close()
    rx_mem.close()
    os.close(mem_fd)


if __name__ == "__main__":
    main()
